### ISSUE TITLE
Error while uploading a new X-image for prediction

### ISSUE THREAD

**Issue by Gpraveenkumar04** [vahiwe/Pneumonia-Prediction-App#6]
Can anyone please help me out to resolve this errors.
requests.exceptions.MissingSchema
requests.exceptions.MissingSchema: Invalid URL 'IP_ROUTE': No scheme supplied. Perhaps you meant http://IP_ROUTE?
![S](https://user-images.githubusercontent.com/55353267/148774169-09b93f48-6a7b-43b7-a0a3-486e67483955.jpg)
.

**Comment by vahiwe** [comment]
Hello @Gpraveenkumar04 
This project hasn’t been updated in a long while
But from what I can remember the ML model needs to be served using a REST API
Here’s a [link](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple#serve_your_model_with_tensorflow_serving) that shows how to get that done.
The `IP_ROUTE` should be replaced by the served ML REST API endpoint 
Check `predict.py` to see what the endpoint looks like.
Let me know if any other issues.

**Comment by Gpraveenkumar04** [comment]
@vahiwe 
Could you please help me out with these Errors. 
![S](https://user-images.githubusercontent.com/55353267/150675830-96802ff4-4af7-4b77-bbfc-6db2b0fbecf0.jpg)

Facing issues while activating the server and making POST requests. 

`` # Creating payload for TensorFlow serving request
        data = json.dumps({"signature_name": "serving_default", "instances": img.tolist()})
        
        # # Making POST request 
        headers = {"content-type": "application/json"}
        json_response = requests.post( "http://localhost:8501/v1/models/saved_model:predict", data=data, headers=headers)

        # Decoding results from TensorFlow Serving server
        predictions = json_response.json()['predictions'][0][0]``

**Comment by vahiwe** [comment]
Sorry for the really late response 🙏🙏
Were you able to get this sorted?
